# Generated by Django 5.2.5 on 2025-08-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Locality', 'verbose_name_plural': 'Localities'},
        ),
    ]
