# Generated by Django 5.2.5 on 2025-08-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastecategory',
            options={'verbose_name': 'Waste Category', 'verbose_name_plural': 'Waste Categories'},
        ),
    ]
