# Generated by Django 5.2.5 on 2025-08-12 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_requests', '0002_initial'),
        ('waste_categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='request',
            name='waste_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='waste_categories.wastecategory'),
            preserve_default=False,
        ),
    ]
