# Generated by Django 5.2.5 on 2025-08-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_requests', '0003_remove_request_waste_type_request_waste_category'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='routes.collectionroute'),
        ),
    ]
