# Generated by Django 5.2.5 on 2025-08-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_requests', '0004_request_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
