# Generated by Django 5.2.5 on 2025-08-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('waste_categories', models.ManyToManyField(related_name='companies', to='waste_categories.wastecategory')),
            ],
        ),
    ]
